### ISSUE TITLE
"WFLYBATCH000004: The service JobOperatorService has been stopped and cannot execute operations" during shutdown

### ISSUE THREAD

**Issue by zdazzy** [wildfly/wildfly#10718]
I get the following while shutting down WildFly 11.0.0.Final with a batchlet running.

```
...
13:20:12,575 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 76) RESTEASY002225: Deploying javax.ws.rs.core.Application: class batchtest.RsApplication$Proxy$_$$_WeldClientProxy
13:20:12,613 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 76) WFLYUT0021: Registered web context: '/batchtest' for server 'default-server'
13:20:12,635 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 43) WFLYSRV0010: Deployed "batchtest-1.0.0-SNAPSHOT.war" (runtime-name : "batchtest-1.0.0-SNAPSHOT.war")
13:20:12,691 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
13:20:12,693 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
13:20:12,693 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
13:20:12,693 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 11.0.0.Final (WildFly Core 3.0.8.Final) started in 10294ms - Started 552 of 794 services (443 services are lazy, passive or on-demand)
<---------- Starting batchlet
13:20:37,715 INFO  [stdout] (Batch Thread - 1) Batchlet started
13:20:37,721 INFO  [stdout] (Batch Thread - 1) Batchlet runnning
13:20:38,722 INFO  [stdout] (Batch Thread - 1) Batchlet runnning
13:20:39,723 INFO  [stdout] (Batch Thread - 1) Batchlet runnning
13:20:40,723 INFO  [stdout] (Batch Thread - 1) Batchlet runnning
13:20:41,724 INFO  [stdout] (Batch Thread - 1) Batchlet runnning
13:20:42,724 INFO  [stdout] (Batch Thread - 1) Batchlet runnning
<---------- Issuing a server "shutdown" command
13:20:43,133 INFO  [org.jboss.as.server] (management-handler-thread - 4) WFLYSRV0236: Suspending server with no timeout.
13:20:43,135 INFO  [org.jboss.as.ejb3] (management-handler-thread - 4) WFLYEJB0493: EJB subsystem suspension complete
13:20:43,137 WARN  [org.wildfly.extension.batch] (management-handler-thread - 4) WFLYBATCH000014: Stopping execution 1 of job1 for deployment batchtest-1.0.0-SNAPSHOT.war
13:20:43,140 INFO  [org.jboss.as.server] (Management Triggered Shutdown) WFLYSRV0241: Shutting down in response to management operation 'shutdown'
13:20:43,178 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 80) WFLYUT0022: Unregistered web context: '/batchtest' from server 'default-server'
13:20:43,185 INFO  [org.wildfly.extension.messaging-activemq] (ServerService Thread Pool -- 76) WFLYMSGAMQ0006: Unbound messaging object to jndi name java:jboss/exported/jms/RemoteConnectionFactory
13:20:43,189 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-7) ISPN000080: Disconnecting JGroups channel ejb
13:20:43,190 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-7) ISPN000082: Stopping the RpcDispatcher for channel ejb
13:20:43,192 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-8) ISPN000080: Disconnecting JGroups channel ejb
13:20:43,193 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-8) ISPN000082: Stopping the RpcDispatcher for channel ejb
13:20:43,193 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-5) ISPN000080: Disconnecting JGroups channel ejb
13:20:43,193 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-5) ISPN000082: Stopping the RpcDispatcher for channel ejb
13:20:43,244 INFO  [org.jboss.modcluster] (ServerService Thread Pool -- 81) MODCLUSTER000002: Initiating mod_cluster shutdown
13:20:43,258 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0019: Host default-host stopping
13:20:43,269 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 81) WFLYCLINF0003: Stopped client-mappings cache from ejb container
13:20:43,274 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000080: Disconnecting JGroups channel ejb
13:20:43,274 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-2) ISPN000082: Stopping the RpcDispatcher for channel ejb
13:20:43,277 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-7) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
13:20:43,277 INFO  [org.wildfly.extension.messaging-activemq] (MSC service thread 1-7) WFLYMSGAMQ0006: Unbound messaging object to jndi name java:jboss/DefaultJMSConnectionFactory
13:20:43,278 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-4) WFLYJCA0011: Unbound JCA ConnectionFactory [java:/JmsXA]
13:20:43,283 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-4) WFLYJCA0019: Stopped Driver service with driver-name = h2
13:20:43,293 INFO  [org.apache.activemq.artemis.ra] (ServerService Thread Pool -- 80) AMQ151003: resource adaptor stopped
13:20:43,321 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-6) WFLYUT0008: Undertow HTTPS listener https suspending
13:20:43,321 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0008: Undertow AJP listener ajp suspending
13:20:43,321 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-6) WFLYUT0007: Undertow HTTPS listener https stopped, was bound to 127.0.0.1:8443
13:20:43,321 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0007: Undertow AJP listener ajp stopped, was bound to 127.0.0.1:8009
13:20:43,324 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0028: Stopped deployment batchtest-1.0.0-SNAPSHOT.war (runtime-name: batchtest-1.0.0-SNAPSHOT.war) in 165ms
13:20:43,398 INFO  [org.apache.activemq.artemis.core.server] (ServerService Thread Pool -- 80) AMQ221002: Apache ActiveMQ Artemis Message Broker version 1.5.5.jbossorg-008 [52931f6c-e156-11e7-aa6d-4c72b920fd53] stopped, uptime 33.299 seconds
13:20:43,399 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0008: Undertow HTTP listener default suspending
13:20:43,399 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 127.0.0.1:8080
13:20:43,400 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0004: Undertow 1.4.18.Final stopping
13:20:43,725 INFO  [stdout] (Batch Thread - 1) Batchlet stopped
13:20:43,728 ERROR [org.jberet] (Batch Thread - 1) JBERET000007: Failed to run job job1, , org.jberet.job.model.Job@31dc14: java.lang.IllegalStateException: WFLYBATCH000004: The service JobOperatorService has been stopped and cannot execute operations.
	at org.wildfly.extension.batch.jberet.job.repository.JobRepositoryService.getAndCheckDelegate(JobRepositoryService.java:203)
	at org.wildfly.extension.batch.jberet.job.repository.JobRepositoryService.savePersistentData(JobRepositoryService.java:189)
	at org.wildfly.extension.batch.jberet.job.repository.InMemoryJobRepositoryService.savePersistentData(InMemoryJobRepositoryService.java:37)
	at org.jberet.runtime.context.StepContextImpl.savePersistentData(StepContextImpl.java:190)
	at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:172)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runFromHeadOrRestartPoint(CompositeExecutionRunner.java:88)
	at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:60)
	at org.wildfly.extension.batch.jberet.deployment.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:184)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

13:20:43,729 ERROR [stderr] (Batch Thread - 1) Exception in thread "Batch Thread - 1" java.lang.IllegalStateException: WFLYBATCH000004: The service JobOperatorService has been stopped and cannot execute operations.
13:20:43,731 ERROR [stderr] (Batch Thread - 1) 	at org.wildfly.extension.batch.jberet.job.repository.JobRepositoryService.getAndCheckDelegate(JobRepositoryService.java:203)
13:20:43,731 ERROR [stderr] (Batch Thread - 1) 	at org.wildfly.extension.batch.jberet.job.repository.JobRepositoryService.updateJobExecution(JobRepositoryService.java:134)
13:20:43,731 ERROR [stderr] (Batch Thread - 1) 	at org.wildfly.extension.batch.jberet.job.repository.InMemoryJobRepositoryService.updateJobExecution(InMemoryJobRepositoryService.java:37)
13:20:43,732 ERROR [stderr] (Batch Thread - 1) 	at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:101)
13:20:43,732 ERROR [stderr] (Batch Thread - 1) 	at org.wildfly.extension.batch.jberet.deployment.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:184)
13:20:43,732 INFO  [org.jboss.as] (MSC service thread 1-5) WFLYSRV0050: WildFly Full 11.0.0.Final (WildFly Core 3.0.8.Final) stopped in 538ms
```
The test batchlet I'm running is quite basic:
```
@Named
public class JobBatchlet
implements Batchlet
{
    private volatile boolean stop;

    @Override
    public String process()
    throws Exception
    {
        System.out.println("Batchlet started");

        while(true)
        {
            System.out.println("Batchlet runnning");

            Thread.sleep(1000L);

            if (stop)
            {
                return null;
            }
        }
    }

    @Override
    public void stop()
    {
        stop = true;
    }
}
```

It is my understanding is that there is a support for graceful shutdown, as can be seen in `org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService#stopRunningJobs()` . But there seems to be a bug in the shutdown order or service dependencies that leads to JobOperatorService being stopped before the jobs are stopped.

Tested on WildFly 10.1.0.Final and WildFly 11.0.0.Final with stock standalone-full-ha.xml.

**Comment by ctomc** [comment]
Please ask questions like that on forums or on wildfly-dev mailing list http://wildfly.org/gethelp/
