### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError:ALLOW_UNESCAPED_CHARACTERS_IN_URL

### ISSUE THREAD

**Issue by narendrakadali** [wildfly/wildfly#11964]
When deploying Wildfly 14, getting the following error 
`
ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:143)
        at org.jboss.as.server.ServerService.boot(ServerService.java:377)
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:372)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException: WFLYCTL0083: Failed to load module org.wildfly.extension.undertow
        at org.jboss.as.controller.parsing.DeferredExtensionContext.load(DeferredExtensionContext.java:100)
        at org.jboss.as.server.parsing.StandaloneXml_8.readServerElement(StandaloneXml_8.java:237)       
	    at org.jboss.as.server.parsing.StandaloneXml_8.readElement(StandaloneXml_8.java:137)
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:120)
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:52)
        at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:122)
        at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:76)
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:126)
        ... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: ALLOW_UNESCAPED_CHARACTERS_IN_URL
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.jboss.as.controller.parsing.DeferredExtensionContext.load(DeferredExtensionContext.java:92)
        ... 10 more
Caused by: java.lang.NoSuchFieldError: ALLOW_UNESCAPED_CHARACTERS_IN_URL
        at org.wildfly.extension.undertow.ListenerResourceDefinition.<clinit>(ListenerResourceDefinition.java:165)
        at org.wildfly.extension.undertow.ServerDefinition.<clinit>(ServerDefinition.java:60)
        at org.wildfly.extension.undertow.UndertowRootDefinition.<clinit>(UndertowRootDefinition.java:107)
        at org.wildfly.extension.undertow.UndertowSubsystemParser_7_0.<init>(UndertowSubsystemParser_7_0.java:55)
        at org.jboss.as.controller.extension.ExtensionRegistry$ExtensionParsingContextImpl.attemptCurrentParserInitialization(ExtensionRegistry.java:507)
        at org.jboss.as.controller.extension.ExtensionRegistry$ExtensionParsingContextImpl.access$200(ExtensionRegistry.java:433)
        at org.jboss.as.controller.extension.ExtensionRegistry.initializeParsers(ExtensionRegistry.java:248)
        at org.jboss.as.controller.parsing.DeferredExtensionContext.loadModule(DeferredExtensionContext.java:116)
        at org.jboss.as.controller.parsing.DeferredExtensionContext.access$000(DeferredExtensionContext.java:44)
        at org.jboss.as.controller.parsing.DeferredExtensionContext$1.call(DeferredExtensionContext.java:74)
        at org.jboss.as.controller.parsing.DeferredExtensionContext$1.call(DeferredExtensionContext.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:485)
`
Following is the environment I am using.

java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by jaikiran** [comment]
Are you doing any changes to the standalone.xml file? It looks like you probably added some attribute that is only supported in a newer schema version of the undertow subsystem, but didn't change the version attribute of the subsystem to a relevant value.

P.S: Questions like these are better answered in the forums here https://developer.jboss.org/en/wildfly/content. Please create a discussion there to continue this discussion, in case you have further queries.

**Comment by dw511214992** [comment]
Hi Narendra,
Have you found the root cause? I encounter the same issue when upgrade keycloak to 4.8.3.
Thanks
Wei
