### ISSUE TITLE
Wildfly16 LoginContext - No LoginModule found for ScramLoginModule

### ISSUE THREAD

**Issue by Sabartius** [wildfly/wildfly#12137]
After Upgrading from Wildfly 15.0.1.Final to Wildfly 16, it's not possible to Authenticate a Kafka-Consumer. 
It seems as if there is something missing in the Wildfly-Security, which was present before.

To reproduce create a Kafka-Consumer with Authentication using following Configuration:

- security.protocol = "SASL_SSL"
- sasl.mechanism = "SCRAM-SHA-512"
- sasl.jaas.config = "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"myUser\" password=\"myPwd\";"

```
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: No LoginModule found for org.apache.kafka.common.security.scram.ScramLoginModule
	at deployment.antrag.war//org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:125)
	at deployment.antrag.war//org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:140)
	at deployment.antrag.war//org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:65)
	at deployment.antrag.war//org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:88)
	at deployment.antrag.war//org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:710)
	... 35 more
Caused by: javax.security.auth.login.LoginException: No LoginModule found for org.apache.kafka.common.security.scram.ScramLoginModule
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:710)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
	at deployment.antrag.war//org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:52)
	at deployment.antrag.war//org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:53)
	at deployment.antrag.war//org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:89)
	at deployment.antrag.war//org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:114)
	... 39 more
```

**Comment by darranl** [comment]
For this issue you will be better to discuss this in the WildFly user forums http://wildfly.org/gethelp/

From the stack trace shown neither of the security projects used within WildFly appear in use here, at this point this would suggest more likely a deployment class loading issue.
