### ISSUE TITLE
Bag with Websockets

### ISSUE THREAD

**Issue by EvytonAcc** [wildfly/wildfly#8452]
Good day, the fourth day in a row looking for an opportunity to correct the error, which is caused when compiling. The same project was launched on Tomcat but Wildfly-9.0.2.Final not start. Help please, can I have a config that messed up, they at me are the default may have to turn somewhere websockets?

Error
```
java.lang.Exception: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host.\"/v-3.0.0\"" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host.\"/v-3.0.0\": java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: rss.WsClientEndpoint.<init>()
    Caused by: java.lang.NoSuchMethodException: rss.WsClientEndpoint.<init>()"}}
```
Full Error
```
ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 28) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host."/v-3.0.0": org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host."/v-3.0.0": java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
	at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:90)
	at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:245)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:150)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more
Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
	at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpointInternal(ServerWebSocketContainer.java:492)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpoint(ServerWebSocketContainer.java:429)
	at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:84)
	... 10 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: rss.WsClientEndpoint.<init>()
	at org.jboss.as.ee.component.ReflectiveClassIntrospector.createFactory(ReflectiveClassIntrospector.java:59)
	at org.jboss.as.ee.component.ComponentRegistry.createInstanceFactory(ComponentRegistry.java:76)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$ComponentClassIntrospector.createInstanceFactory(UndertowDeploymentInfoService.java:1338)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpointInternal(ServerWebSocketContainer.java:486)
	... 12 more
Caused by: java.lang.NoSuchMethodException: rss.WsClientEndpoint.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.jboss.as.ee.component.ReflectiveClassIntrospector.createFactory(ReflectiveClassIntrospector.java:57)
	... 15 more

2015-12-03 15:56:35,386 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 2) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "v-3.0.0.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host.\"/v-3.0.0\"" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host.\"/v-3.0.0\": java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: rss.WsClientEndpoint.<init>()
    Caused by: java.lang.NoSuchMethodException: rss.WsClientEndpoint.<init>()"}}
2015-12-03 15:56:35,387 ERROR [org.jboss.as.server] (management-handler-thread - 2) WFLYSRV0021: Deploy of deployment "v-3.0.0.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host.\"/v-3.0.0\"" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host.\"/v-3.0.0\": java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
    Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: rss.WsClientEndpoint.<init>()
    Caused by: java.lang.NoSuchMethodException: rss.WsClientEndpoint.<init>()"}}
```

build.gradle
```
apply plugin: 'java'
apply plugin: 'war'

war {
    baseName = 'v'
    version =  '3.0.0'
}

sourceCompatibility = 1.5
version = '1.0'

configurations {
    provided
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'
}

repositories {
    mavenCentral()
    maven { url "http://repo.spring.io/libs-snapshot" }
}

dependencies {

    compile ("javax.websocket:javax.websocket-api:1.0")
    compile ("javax.servlet:servlet-api:2.5")

    compile("org.springframework.boot:spring-boot-starter-web:1.2.7.RELEASE")
            {
                exclude group: 'org.springframework.boot',module:'spring-boot-starter-tomcat'
            }
    compile('org.springframework.boot:spring-boot-starter-test')

    compile('org.springframework.boot:spring-boot-starter-data-elasticsearch:1.2.0.RELEASE')
    compile 'org.springframework.social:spring-social-facebook:2.0.1.RELEASE'
    compile("org.hibernate:hibernate-core:5.0.1.Final")
    compile("org.hibernate:hibernate-entitymanager:5.0.1.Final")
    compile("org.hibernate:hibernate-c3p0:5.0.3.Final")
    compile('org.postgresql:postgresql:9.4-1205-jdbc42')
    compile('com.fasterxml.jackson.core:jackson-annotations:2.6.3')
    compile('com.fasterxml.jackson.core:jackson-core:2.6.3')
    compile('com.fasterxml.jackson.core:jackson-databind:2.6.3')
    compile('com.mchange:c3p0:0.9.5.1')
    compile('com.rometools:rome:1.5.0')
}

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'http://repo.spring.io/libs-release' }
    }
    dependencies {
        classpath('org.springframework.boot:spring-boot-gradle-plugin:1.1.8.RELEASE')
    }
}

apply plugin: 'spring-boot'

```
class WsClientEndpoint
```
package rss;

import javax.websocket.*;
import java.net.URI;

@ClientEndpoint
public class WsClientEndpoint {
    private Session userSession = null;
    private MessageHandler messageHandler;

    public WsClientEndpoint(final URI endpointURI) {
        try {
            WebSocketContainer container = ContainerProvider.getWebSocketContainer();
            container.connectToServer(this, endpointURI);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @OnOpen
    public void onOpen(final Session userSession) {
        this.userSession = userSession;
    }

    @OnClose
    public void onClose(final Session userSession, final CloseReason reason) {
        this.userSession = null;
    }

    @OnMessage
    public void onMessage(final String message) {
        if (messageHandler != null) {
            messageHandler.handleMessage(message);
        }
    }

    public void addMessageHandler(final MessageHandler msgHandler) {
        messageHandler = msgHandler;
    }

    public void sendMessage(final String message) {
        userSession.getAsyncRemote().sendText(message);
    }

    public static interface MessageHandler {
        public void handleMessage(String message);
    }
}
```

**Comment by langfr** [comment]
java.lang.NoSuchMethodException: rss.WsClientEndpoint.<init>()
Add a parameterless constructor to your class.
And post such questions at https://developer.jboss.org/en/wildfly/content/ next time.

**Comment by ctomc** [comment]
As @langfr said this belongs to forums no github issues.
in any case this two deps 
compile ("javax.websocket:javax.websocket-api:1.0")
compile ("javax.servlet:servlet-api:2.5")
should be scope provided.

**Comment by EvytonAcc** [comment]
@langfr  Thank you very much, it works!
