### ISSUE TITLE
Unable to deploy postgre-datasource to 10.1.0.Final

### ISSUE THREAD

**Issue by grischan** [wildfly/wildfly#9138]
Hello,

I've just updated my installation of wildfly from 10.0.0 to 10.1.0.

The deployment of a postgre-datasource fails since the upgrade. I also tried a fresh installation of 10.1.0.

The driver is added as module:
`<module xmlns="urn:jboss:module:1.1" name="org.postgres">
  <resources>
    <resource-root path="postgresql-9.4.1208.jar"></resource-root>
  </resources>
  <dependencies>
    <module name="javax.api" />
    <module name="javax.transaction.api" />
	<module name="javax.servlet.api" optional="true"/>
  </dependencies>
</module>`

The datasource is defined in the standalone.xml:
`<datasource jndi-name="java:jboss/datasources/pro" pool-name="proDS" enabled="true" use-java-context="true" use-ccm="true">
                    <connection-url>jdbc:postgresql://localhost:5432/proDB</connection-url>
                    <driver>postgres</driver>
                    <pool>
                        <min-pool-size>5</min-pool-size>
                        <initial-pool-size>5</initial-pool-size>
                        <max-pool-size>20</max-pool-size>
                        <prefill>true</prefill>
                    </pool>
                    <security>
                        <user-name>******</user-name>
                        <password>******</password>
                    </security>
                    <validation>
                        <valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker"/>
                        <exception-sorter class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter"/>
                    </validation>
                    <statement>
                        <prepared-statement-cache-size>100</prepared-statement-cache-size>
                        <share-prepared-statements>true</share-prepared-statements>
                    </statement>
                </datasource>
<drivers>
                    <driver name="postgres" module="org.postgres">
                        <datasource-class>org.postgresql.ds.PGSimpleDataSource</datasource-class>
                    </driver>
                </drivers>`

On startup the following error occurs:
`18:05:59,482 ERROR [org.jboss.as.connector.subsystems.datasources.AbstractDataSourceService$AS7DataSourceDeployer] (MSC service thread 1-8) Error during the deployment of java:jboss/datasources/pro: javax.resource.ResourceException: IJ031103: At least one connection property must be defined for datasource-class: org.postgresql.ds.PGSimpleDataSource
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createConnectionFactory(LocalManagedConnectionFactory.java:108)
	at org.jboss.jca.deployers.common.AbstractDsDeployer.deployDataSource(AbstractDsDeployer.java:772)
	at org.jboss.jca.deployers.common.AbstractDsDeployer.createObjectsAndInjectValue(AbstractDsDeployer.java:312)
	at org.jboss.as.connector.subsystems.datasources.AbstractDataSourceService$AS7DataSourceDeployer.deploy(AbstractDataSourceService.java:371)
	at org.jboss.as.connector.subsystems.datasources.AbstractDataSourceService.start(AbstractDataSourceService.java:149)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

18:05:59,483 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service org.wildfly.data-source.devproDS: org.jboss.msc.service.StartException in service org.wildfly.data-source.devproDS: WFLYJCA0033: Error during the deployment of devproDS
	at org.jboss.as.connector.subsystems.datasources.AbstractDataSourceService.start(AbstractDataSourceService.java:163)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.msc.service.StartException in anonymous service: WFLYJCA0032: Unable to start the ds because it generated more than one cf
	at org.jboss.as.connector.subsystems.datasources.AbstractDataSourceService.start(AbstractDataSourceService.java:151)
	... 5 more

18:05:59,620 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-1) WFLYDM0111: Keystore C:\Dev\server\wildfly10\standalone\configuration\application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
18:05:59,666 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-3) WFLYDS0013: Started FileSystemDeploymentService for directory C:\Dev\server\wildfly10\standalone\deployments
18:05:59,814 INFO  [org.infinispan.factories.GlobalComponentRegistry] (MSC service thread 1-7) ISPN000128: Infinispan version: Infinispan 'Chakra' 8.2.4.Final
18:05:59,820 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0006: Undertow HTTPS listener https listening on 127.0.0.1:8443
18:05:59,875 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 59) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
18:05:59,875 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 61) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
18:05:59,876 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 59) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
18:05:59,876 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 61) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
18:05:59,881 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 58) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
18:05:59,882 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 58) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
18:05:59,933 INFO  [org.jboss.ws.common.management] (MSC service thread 1-1) JBWS022052: Starting JBossWS 5.1.5.Final (Apache CXF 3.1.6) 
18:05:59,935 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "proDS")
]) - failure description: {
    "WFLYCTL0080: Failed services" => {"org.wildfly.data-source.proDS" => "org.jboss.msc.service.StartException in service org.wildfly.data-source.proDS: WFLYJCA0033: Error during the deployment of proDS
    Caused by: org.jboss.msc.service.StartException in anonymous service: WFLYJCA0032: Unable to start the ds because it generated more than one cf"},
    "WFLYCTL0412: Required services that are not installed:" => ["org.wildfly.data-source.proDS"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
18:05:59,938 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "devproDS")
]) - failure description: {
    "WFLYCTL0080: Failed services" => {"org.wildfly.data-source.proDS" => "org.jboss.msc.service.StartException in service org.wildfly.data-source.proDS: WFLYJCA0033: Error during the deployment of proDS
    Caused by: org.jboss.msc.service.StartException in anonymous service: WFLYJCA0032: Unable to start the ds because it generated more than one cf"},
    "WFLYCTL0412: Required services that are not installed:" => [
        "org.wildfly.data-source.proDS",
        "org.wildfly.data-source.proDS"
    ],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}`

There are several closed jira-tickets regarding this problem. The configuration worked for 10.0.0 and is broken with 10.1.0.

**Comment by grischan** [comment]
Sry, I dont see the nee JIRA. Move the issue.
